#!/bin/bash
mogrify -resize 968x648 /home/pi/photobooth_images/*.jpg
montage /home/pi/photobooth_images/*.jpg -tile 1x3 -geometry +10+10 /home/pi/temp_montage2.jpg
# montage /home/pi/temp_montage2.jpg /home/pi/photobooth_label.jpg -tile 2x1 -geometry +5+5 /home/pi/temp_montage3.jpg
lp -p 1 -d Canon_CP910 /home/pi/temp_montage2.jpg
sleep 50

# TODO: Printer can get stuck after first print. Need a Workaround! Printer Canon CP910

# put picture into archive:
suffix=$(date +%y%m%d_%H%M%S)
cp /home/pi/temp_montage2.jpg /home/pi/PB_archive/PB_${suffix}.jpg
rm /home/pi/photobooth_images/*.jpg
rm /home/pi/temp*
